深尾京司, 牧野達治, & 攝津斉彦. (2019). 日本経済の成長会計分析: 1885-1970 年.

In [1]:
import tabula

In [24]:
url = "http://www.ier.hit-u.ac.jp/Common/publication/DP/DPS-A692.pdf" 
tables = tabula.read_pdf(url, pandas_options={'header':3}, pages=23)

In [32]:
table1 = tables[0][3:].rename(columns={'Unnamed: 0': 'year'})

In [33]:
table1

,year,(1),(2),(3),(4),(5),(6),(7),(8),(9),...,(28),(29),(30),(31),(32),(33),(34),(35),(36),(37)
3,1874,"1,011",716.8,427.1,65.3,22.9,201.5,"4,044.9","1,743.5",260.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan
4,1875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan
5,1876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan
6,1877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan
7,1878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,1936,"2,507","21,038.6","3,575.7","6,141.9","1,476.1","7,358.5","2,486.4","20,221.8","3,342.2",...,54.5%,12.7%,32.9%,61.0%,39.0%,1.031,1.049,1.028,"20,222.1",1.02
66,1937,"2,563","24,137.7","4,027.4","7,313.6","1,781.9","8,083.6","2,931.2","20,817.4","3,373.8",...,55.4%,12.2%,32.3%,59.9%,40.1%,1.038,1.068,1.032,"20,815.4",1.29
67,1938,"2,677","27,686.6","4,219.3","9,837.7","1,896.3","8,574.0","3,159.4","21,863.0","3,216.3",...,53.9%,13.5%,32.7%,57.7%,42.3%,1.064,1.021,1.072,"21,848.0",1.50
68,1939,"3,021","34,015.6","6,072.4","12,463.3","2,357.7","9,552.4","3,569.7","24,815.6","3,412.2",...,54.5%,13.1%,32.4%,59.3%,40.7%,1.165,1.081,1.181,"24,753.4",1.60
69,1940,"3,071","39,258.8","6,668.0","14,588.9","2,810.6","11,097.3","4,094.0","25,346.0","3,266.5",...,50.1%,16.6%,33.3%,57.9%,42.1%,1.149,1.032,1.173,"25,205.0",1.80

In [53]:
tables = tabula.read_pdf(url,lattice=True,pandas_options={'header':3}, pages=24)
table2 = tables[0][3:].rename(columns={'Unnamed: 0': 'year'}).dropna(axis=1)

In [57]:
table2

,year,(1),(6),(7),(8),(9),(10),(12),(13),(14),...,(22),(23),(24),(25),(26),(27),(28),(29),(30),(31)
3,1937,"2,563","14,380.2","3,922.4","2,995.8","7,462.0","70,725","32,156","14,311","7,720",...,5.4%,55.4%,12.2%,32.3%,59.9%,40.1%,0.450,0.920,0.513,"13,285.8"
4,1938,"2,677","14,671.0","3,739.3","3,515.1","7,416.5","71,103","32,290","14,199","8,226",...,5.0%,53.9%,13.5%,32.7%,57.7%,42.3%,0.461,0.880,0.533,"13,944.9"
5,1939,"3,021","16,531.7","3,967.1","4,013.6","8,551.1","71,517","32,652","14,186","8,512",...,5.8%,54.5%,13.1%,32.4%,59.3%,40.7%,0.505,0.932,0.587,"15,799.3"
6,1940,"3,071","16,720.0","3,797.7","4,189.9","8,732.5","71,869","32,942","14,173","8,729",...,4.4%,69.6%,4.6%,25.8%,57.9%,42.1%,0.498,0.890,0.583,"16,087.6"
7,1941,"3,136","16,951.8","3,499.9","4,392.3","9,059.7","72,218","33,018","14,243","9,297",...,3.4%,71.1%,4.9%,24.0%,55.2%,44.8%,0.500,0.818,0.593,"16,432.3"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,1966,"6,506","47,792.8","5,193.7","17,395.1","25,204.0","99,054","50,806","12,032","17,442",...,2.1%,61.4%,16.1%,22.5%,71.6%,28.4%,0.775,1.155,0.772,"47,627.2"
33,1967,"7,152","53,473.8","5,213.6","20,093.3","28,166.8","100,243","52,048","11,796","18,330",...,1.9%,59.9%,18.6%,21.5%,70.7%,29.3%,0.824,1.157,0.820,"53,368.4"
34,1968,"7,983","59,974.2","5,005.2","23,305.1","31,663.9","101,408","52,819","11,518","18,555",...,1.7%,60.8%,18.0%,21.2%,68.7%,31.3%,0.879,1.105,0.878,"59,918.0"
35,1969,"8,874","67,732.5","4,966.5","27,575.6","35,190.3","102,648","53,563","11,246","18,970",...,1.5%,60.7%,18.3%,21.0%,68.6%,31.4%,0.943,1.093,0.942,"67,707.1"
36,1970,"9,714","75,759.9","4,488.0","32,672.8","38,599.1","103,720","54,432","10,736","19,207",...,1.2%,61.2%,18.5%,20.3%,68.5%,31.5%,1.000,1.000,1.000,"75,759.9"